<?php
// database/seeders/OrganizacionSocialSeeder.php

namespace Database\Seeders;

use App\Models\OrganizacionSocial;
use Illuminate\Database\Seeder;

class OrganizacionSocialSeeder extends Seeder
{
    public function run()
    {
        $organizacionesSociales = [
            // 🌽 1. SECTOR ARTESANAL Y PRODUCTIVO
            [
                'nombre' => 'COCEDAL - CONFEDERACIÓN NACIONAL DE COMERCIANTES, ARTESANOS Y MICROEMPRESARIOS EN DESARROLLO DE BOLIVIA',
                'descripcion' => 'FUNDADA EN 1995, REPRESENTA A MÁS DE 50,000 AFILIADOS EN TODO EL PAÍS. SE DEDICA A LA CAPACITACIÓN, ASESORÍA LEGAL Y PROMOCIÓN COMERCIAL DE SUS AFILIADOS. ORGANIZA FERIAS NACIONALES E INTERNACIONALES PARA ARTESANOS Y MICROEMPRESARIOS. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CONAMYPE - CONFEDERACIÓN NACIONAL DE MICRO Y PEQUEÑAS EMPRESAS',
                'descripcion' => 'PRINCIPAL ORGANIZACIÓN REPRESENTANTE DE LAS MIPYMES EN BOLIVIA. GESTIONA PROGRAMAS DE CAPACITACIÓN, ACCESO A CRÉDITO Y FOMENTO A LA COMPETITIVIDAD. CUENTA CON REPRESENTACIÓN EN LOS 9 DEPARTAMENTOS. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CADEPIA - CÁMARA DEPARTAMENTAL DE LA PEQUEÑA INDUSTRIA Y ARTESANÍA',
                'descripcion' => 'EXISTE UNA POR CADA DEPARTAMENTO. PROMUEVE EL DESARROLLO DE LA PEQUEÑA INDUSTRIA Y LA ARTESANÍA LOCAL. BRINDA ASESORÍA TÉCNICA, LEGAL Y COMERCIAL A SUS AFILIADOS. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: DEPARTAMENTAL.'
            ],
            [
                'nombre' => 'CONAMYPE-BOLIVIA - CONFEDERACIÓN DE LA MICRO Y PEQUEÑA EMPRESA DE BOLIVIA',
                'descripcion' => 'ORGANIZACIÓN ESPECIALIZADA EN LA DEFENSA DE LOS DERECHOS DE LAS MIPYMES. PARTICIPA ACTIVAMENTE EN LA FORMULACIÓN DE POLÍTICAS PÚBLICAS PARA EL SECTOR. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FEDEMYPE - FEDERACIONES DEPARTAMENTALES DE LA MICRO Y PEQUEÑA EMPRESA',
                'descripcion' => 'ESTRUCTURA FEDERATIVA QUE COORDINA LAS ACTIVIDADES DE LAS MIPYMES A NIVEL DEPARTAMENTAL. FORTALECE LAS CADENAS PRODUCTIVAS LOCALES Y REGIONALES. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: DEPARTAMENTAL.'
            ],
            [
                'nombre' => 'CONACOP - CONFEDERACIÓN NACIONAL DE COOPERATIVAS DE PRODUCCIÓN',
                'descripcion' => 'REPRESENTA A COOPERATIVAS DE DIVERSOS RUBROS PRODUCTIVOS. PROMUEVE EL MODELO COOPERATIVO Y LA ECONOMÍA SOLIDARIA. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CONFAL - CONFEDERACIÓN DE FABRICANTES DE LADRILLOS',
                'descripcion' => 'AGRUPACIÓN ESPECIALIZADA DE FABRICANTES DE MATERIALES DE CONSTRUCCIÓN. GESTIONA ACCESO A MATERIAS PRIMAS Y TECNOLOGÍAS MEJORADAS. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CONART - CONFEDERACIÓN NACIONAL DE ARTESANOS DE BOLIVIA',
                'descripcion' => 'REPRESENTA A ARTESANOS TRADICIONALES Y CONTEMPORÁNEOS. PRESERVA Y PROMUEVE LAS TÉCNICAS ARTESANALES ANCESTRALES. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'ASME - ASOCIACIONES DE MICROEMPRESARIOS Y EMPRENDEDORES',
                'descripcion' => 'RED DE ASOCIACIONES LOCALES QUE FORTALECEN EL EMPRENDEDURISMO. OFRECE SERVICIOS DE INCUBACIÓN Y ACELERACIÓN DE NEGOCIOS. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: LOCAL.'
            ],
            [
                'nombre' => 'ASARBOLSE - ASOCIACIÓN DE ARTESANOS BOLIVIANOS DEL SECTOR DE CUERO',
                'descripcion' => 'ESPECIALIZADA EN ARTESANÍAS DE CUERO Y PIELES. PROMUEVE LA CALIDAD Y DISEÑO EN PRODUCTOS DE MARROQUINERÍA. SECTOR: ARTESANAL Y PRODUCTIVO. ALCANCE: NACIONAL.'
            ],

            // 🌽 2. SECTOR AGROPECUARIO Y AGROINDUSTRIAL
            [
                'nombre' => 'CSUTCB - CONFEDERACIÓN SINDICAL ÚNICA DE TRABAJADORES CAMPESINOS DE BOLIVIA',
                'descripcion' => 'FUNDADA EN 1979, ES LA PRINCIPAL ORGANIZACIÓN CAMPESINA DEL PAÍS. HISTÓRICAMENTE HA SIDO PROTAGONISTA EN LAS LUCHAS SOCIALES Y AGRARIAS. REPRESENTA A MILLONES DE CAMPESINOS E INDÍGENAS. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CIDOB - CONFEDERACIÓN DE PUEBLOS INDÍGENAS DE BOLIVIA',
                'descripcion' => 'REPRESENTA A 34 PUEBLOS INDÍGENAS DE LAS TIERRAS BAJAS. LUCHA POR LA DEFENSA DE TERRITORIOS, AUTONOMÍAS Y DERECHOS COLECTIVOS. CLAVE EN PROCESOS CONSTITUYENTES Y LEGISLATIVOS. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CONAMAQ - CONSEJO NACIONAL DE AYLLUS Y MARKAS DEL QULLASUYU',
                'descripcion' => 'ORGANIZACIÓN BASADA EN LA ESTRUCTURA TRADICIONAL ANDINA DE AYLLUS. DEFIENDE LOS SISTEMAS DE ORGANIZACIÓN ANCESTRAL Y TERRITORIALIDAD INDÍGENA. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FENCA - FEDERACIÓN NACIONAL DE CAMPESINOS',
                'descripcion' => 'PROMUEVE LA AGRICULTURA FAMILIAR Y SOSTENIBLE. GESTIONA PROGRAMAS DE ASISTENCIA TÉCNICA Y COMERCIALIZACIÓN AGRÍCOLA. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FENECOP - FEDERACIÓN NACIONAL DE COOPERATIVAS AGROPECUARIAS',
                'descripcion' => 'INTEGRA A COOPERATIVAS DE PRODUCCIÓN AGROPECUARIA DIVERSIFICADA. FORTALECE LA COMERCIALIZACIÓN CONJUNTA Y EL ACCESO A MERCADOS. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'AOPEB - ASOCIACIÓN DE ORGANIZACIONES DE PRODUCTORES ECOLÓGICOS DE BOLIVIA',
                'descripcion' => 'PIONERA EN LA PROMOCIÓN DE LA AGRICULTURA ECOLÓGICA CERTIFICADA. CUENTA CON MÁS DE 60,000 PRODUCTORES CERTIFICADOS. EXPORTA PRODUCTOS ORGÁNICOS A MERCADOS INTERNACIONALES. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CAPPO - CÁMARAS DE PRODUCTORES DE OLEAGINOSAS',
                'descripcion' => 'ESPECIALIZADA EN CULTIVOS DE SOYA, GIRASOL, SÁBILA Y OTROS. INVESTIGA Y PROMUEVE TECNOLOGÍAS PARA EL MEJORAMIENTO PRODUCTIVO. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: REGIONAL.'
            ],
            [
                'nombre' => 'CAO - CÁMARA AGROPECUARIA DEL ORIENTE',
                'descripcion' => 'PRINCIPAL ENTIDAD DEL AGRO EN SANTA CRUZ. REPRESENTA A GRANDES, MEDIANOS Y PEQUEÑOS PRODUCTORES. CLAVE EN LA PRODUCCIÓN DE ALIMENTOS PARA EL PAÍS. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: REGIONAL.'
            ],
            [
                'nombre' => 'ANPROCA - ASOCIACIÓN NACIONAL DE PRODUCTORES DE CACAO',
                'descripcion' => 'PROMUEVE EL CULTIVO SOSTENIBLE DE CACAO FINO Y DE AROMA. FORTALECE LA CADENA PRODUCTIVA DESDE LA PRODUCCIÓN HASTA LA COMERCIALIZACIÓN. SECTOR: AGROPECUARIO Y AGROINDUSTRIAL. ALCANCE: NACIONAL.'
            ],

            // 🚚 3. SECTOR TRANSPORTE
            [
                'nombre' => 'CONTRABOL - CONFEDERACIÓN NACIONAL DEL TRANSPORTE PESADO DE BOLIVIA',
                'descripcion' => 'REPRESENTA A TRANSPORTISTAS DE CARGA PESADA EN RUTAS NACIONALES E INTERNACIONALES. GESTIONA TARIFAS, SEGUROS Y CONDICIONES LABORALES DEL SECTOR. SECTOR: TRANSPORTE. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FENATRAMB - FEDERACIÓN NACIONAL DE TRANSPORTE MIXTO DE BOLIVIA',
                'descripcion' => 'AGRUPACIÓN DE TRANSPORTISTAS QUE COMBINAN PASAJEROS Y CARGA. OPERA PRINCIPALMENTE EN RUTAS INTERDEPARTAMENTALES Y REGIONALES. SECTOR: TRANSPORTE. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FENATTRANS - FEDERACIÓN NACIONAL DEL TRANSPORTE SINDICALIZADO',
                'descripcion' => 'ORGANIZACIÓN SINDICAL CON FUERTE PRESENCIA EN EL TRANSPORTE URBANO. NEGOCIA CONVENIOS COLECTIVOS Y CONDICIONES LABORALES. SECTOR: TRANSPORTE. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FEDETRANS - FEDERACIONES DEPARTAMENTALES DE TRANSPORTE',
                'descripcion' => 'COORDINAN EL TRANSPORTE INTRA-DEPARTAMENTAL Y REGULAN LAS RUTAS LOCALES. GESTIONAN CON LAS AUTORIDADES LOCALES LOS PERMISOS Y OPERACIONES. SECTOR: TRANSPORTE. ALCANCE: DEPARTAMENTAL.'
            ],
            [
                'nombre' => 'COOTRANS - COOPERATIVAS DE TRANSPORTE',
                'descripcion' => 'ORGANIZACIONES COOPERATIVAS QUE PRESTAN SERVICIOS DE TRANSPORTE URBANO. OFRECEN SERVICIOS EN LAS PRINCIPALES CIUDADES DEL PAÍS. SECTOR: TRANSPORTE. ALCANCE: URBANO.'
            ],

            // 🏭 4. SECTOR INDUSTRIAL, COMERCIAL Y EMPRESARIAL
            [
                'nombre' => 'CEPB - CONFEDERACIÓN DE EMPRESARIOS PRIVADOS DE BOLIVIA',
                'descripcion' => 'MÁXIMA ENTIDAD EMPRESARIAL DEL PAÍS, FUNDADA EN 1959. AGRUPA A LAS PRINCIPALES CÁMARAS SECTORIALES Y DEPARTAMENTALES. PARTICIPA ACTIVAMENTE EN EL DIÁLOGO SOCIAL Y ECONÓMICO. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CNI - CÁMARA NACIONAL DE INDUSTRIAS',
                'descripcion' => 'REPRESENTA AL SECTOR INDUSTRIAL MANUFACTURERO EN BOLIVIA. PROMUEVE LA COMPETITIVIDAD, INNOVACIÓN Y DESARROLLO TECNOLÓGICO. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CNC - CÁMARA NACIONAL DE COMERCIO',
                'descripcion' => 'DEFIENDE LOS INTERESES DEL SECTOR COMERCIAL FORMAL. PROMUEVE EL COMERCIO INTERNO Y LAS RELACIONES COMERCIALES INTERNACIONALES. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CADEX - CÁMARA DE EXPORTADORES',
                'descripcion' => 'ESPECIALIZADA EN EL FOMENTO DE LAS EXPORTACIONES BOLIVIANAS. BRINDA ASESORÍA EN COMERCIO EXTERIOR Y ACCESO A MERCADOS INTERNACIONALES. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CADECA - CÁMARAS DEPARTAMENTALES DE COMERCIO',
                'descripcion' => 'REPRESENTAN AL COMERCIO FORMAL EN CADA DEPARTAMENTO. GESTIONAN ANTE AUTORIDADES LOCALES TEMAS COMERCIALES Y TRIBUTARIOS. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: DEPARTAMENTAL.'
            ],
            [
                'nombre' => 'CANEB - CÁMARA NACIONAL DE EXPORTADORES DE BOLIVIA',
                'descripcion' => 'PROMUEVE LA DIVERSIFICACIÓN DE LAS EXPORTACIONES BOLIVIANAS. CAPACITA EN NORMATIVAS INTERNACIONALES Y LOGÍSTICA DE EXPORTACIÓN. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FEPC - FEDERACIÓN DE ENTIDADES EMPRESARIALES PRIVADAS DE COCHABAMBA',
                'descripcion' => 'COORDINA LAS ACTIVIDADES EMPRESARIALES EN EL DEPARTAMENTO DE COCHABAMBA. PROMUEVE EL DESARROLLO ECONÓMICO REGIONAL Y LA INVERSIÓN. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: DEPARTAMENTAL.'
            ],
            [
                'nombre' => 'FEPSC - FEDERACIÓN DE EMPRESARIOS PRIVADOS DE SANTA CRUZ',
                'descripcion' => 'PRINCIPAL ENTIDAD EMPRESARIAL DEL ORIENTE BOLIVIANO. REPRESENTA A LOS SECTORES PRODUCTIVOS MÁS DINÁMICOS DEL PAÍS. SECTOR: INDUSTRIAL, COMERCIAL Y EMPRESARIAL. ALCANCE: DEPARTAMENTAL.'
            ],

            // ⛏ 5. SECTOR MINERO
            [
                'nombre' => 'FSTMB - FEDERACIÓN SINDICAL DE TRABAJADORES MINEROS DE BOLIVIA',
                'descripcion' => 'HISTÓRICA ORGANIZACIÓN FUNDADA EN 1944, PROTAGONISTA DE LA REVOLUCIÓN NACIONAL DE 1952. REPRESENTA A TRABAJADORES DE LA MINERÍA MEDIANA Y ESTATAL. SECTOR: MINERO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FENCOMIN - FEDERACIÓN NACIONAL DE COOPERATIVAS MINERAS',
                'descripcion' => 'REPRESENTA A MÁS DE 150,000 COOPERATIVISTAS MINEROS. GESTIONA DERECHOS DE EXPLOTACIÓN Y COMERCIALIZACIÓN DE MINERALES. SECTOR: MINERO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CONCOBM - CONFEDERACIÓN DE COOPERATIVAS MINERAS DE BOLIVIA',
                'descripcion' => 'MÁXIMA INSTANCIA DEL SECTOR COOPERATIVO MINERO. NEGOCIA POLÍTICAS SECTORIALES Y CONDICIONES DE TRABAJO. SECTOR: MINERO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FEDECOMIN - FEDERACIONES DEPARTAMENTALES DE COOPERATIVAS MINERAS',
                'descripcion' => 'COORDINAN LA ACTIVIDAD MINERA COOPERATIVA A NIVEL DEPARTAMENTAL. GESTIONAN PERMISOS Y RELACIONES CON AUTORIDADES LOCALES. SECTOR: MINERO. ALCANCE: DEPARTAMENTAL.'
            ],

            // 👷 6. SECTOR LABORAL Y SINDICAL ECONÓMICO
            [
                'nombre' => 'COB - CENTRAL OBRERA BOLIVIANA',
                'descripcion' => 'MÁXIMA ORGANIZACIÓN SINDICAL DEL PAÍS, FUNDADA EN 1952. AGRUPA A TODAS LAS FEDERACIONES Y CONFEDERACIONES DE TRABAJADORES. HISTÓRICAMENTE HA TENIDO GRAN INFLUENCIA POLÍTICA Y SOCIAL. SECTOR: LABORAL Y SINDICAL ECONÓMICO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'COD - CENTRALES OBRERAS DEPARTAMENTALES',
                'descripcion' => 'ESTRUCTURAS DEPARTAMENTALES DE LA COB EN CADA REGIÓN. COORDINAN LAS LUCHAS Y DEMANDAS LABORALES A NIVEL REGIONAL. SECTOR: LABORAL Y SINDICAL ECONÓMICO. ALCANCE: DEPARTAMENTAL.'
            ],
            [
                'nombre' => 'FAM - FEDERACIÓN DE ASOCIACIONES MUNICIPALES',
                'descripcion' => 'REPRESENTA A LOS GOBIERNOS AUTÓNOMOS MUNICIPALES ANTE INSTANCIAS NACIONALES. GESTIONA TRANSFERENCIAS Y COMPETENCIAS MUNICIPALES. SECTOR: LABORAL Y SINDICAL ECONÓMICO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FES - FEDERACIONES DE EMPLEADOS DE SERVICIOS',
                'descripcion' => 'AGRUPAN A TRABAJADORES DE SECTORES COMO SALUD, EDUCACIÓN, BANCA Y SERVICIOS PÚBLICOS. NEGOCIAN CONVENIOS COLECTIVOS SECTORIALES. SECTOR: LABORAL Y SINDICAL ECONÓMICO. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'CSTB - CONFEDERACIÓN SINDICAL DE TRABAJADORES DE BOLIVIA',
                'descripcion' => 'ORGANIZACIÓN SINDICAL QUE COMPLEMENTA LA ESTRUCTURA DE LA COB. REPRESENTA A TRABAJADORES DE SECTORES ESPECÍFICOS Y EMPRESAS PRIVADAS. SECTOR: LABORAL Y SINDICAL ECONÓMICO. ALCANCE: NACIONAL.'
            ],

            // 🧺 7. ECONOMÍA POPULAR Y SOLIDARIA
            [
                'nombre' => 'CONACOOP - CONFEDERACIÓN NACIONAL DE COOPERATIVAS',
                'descripcion' => 'REPRESENTA A COOPERATIVAS DE AHORRO Y CRÉDITO, CONSUMO, PRODUCCIÓN Y SERVICIOS. PROMUEVE LOS PRINCIPIOS COOPERATIVOS A NIVEL NACIONAL. SECTOR: ECONOMÍA POPULAR Y SOLIDARIA. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'COFECAY - CONSEJO DE FEDERACIONES CAMPESINAS',
                'descripcion' => 'COORDINA LAS DEMANDAS Y PROPUESTAS DEL SECTOR CAMPESINO A NIVEL NACIONAL. ARTICULA CON OTRAS ORGANIZACIONES SOCIALES Y DEL ESTADO. SECTOR: ECONOMÍA POPULAR Y SOLIDARIA. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FEJUVE - FEDERACIONES DE JUNTAS VECINALES',
                'descripcion' => 'REPRESENTAN A VECINOS ORGANIZADOS EN BARRIOS Y URBANIZACIONES. GESTIONAN OBRAS PÚBLICAS, SERVICIOS BÁSICOS Y SEGURIDAD CIUDADANA. SECTOR: ECONOMÍA POPULAR Y SOLIDARIA. ALCANCE: URBANO.'
            ],
            [
                'nombre' => 'COFECOM - CONFEDERACIÓN DE COMERCIANTES MINORISTAS',
                'descripcion' => 'DEFIENDE LOS INTERESES DE COMERCIANTES DE MERCADOS, FERIAS Y PEQUEÑOS NEGOCIOS. GESTIONA CONDICIONES TRIBUTARIAS Y DE FORMALIZACIÓN. SECTOR: ECONOMÍA POPULAR Y SOLIDARIA. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'FERICOMIN - FEDERACIONES DE COMERCIANTES INTERCULTURALES',
                'descripcion' => 'PROMUEVE EL COMERCIO ENTRE DIFERENTES CULTURAS Y REGIONES. FORTALECE LOS INTERCAMBIOS COMERCIALES TRADICIONALES Y MODERNOS. SECTOR: ECONOMÍA POPULAR Y SOLIDARIA. ALCANCE: NACIONAL.'
            ],
            [
                'nombre' => 'ASOFOP - ASOCIACIONES DE FERIAS Y MERCADOS POPULARES',
                'descripcion' => 'ORGANIZAN Y GESTIONAN FERIAS SEMANALES Y MERCADOS TRADICIONALES. PROMUEVEN EL COMERCIO JUSTO Y EL CONSUMO LOCAL. SECTOR: ECONOMÍA POPULAR Y SOLIDARIA. ALCANCE: LOCAL.'
            ]
        ];

        foreach ($organizacionesSociales as $organizacion) {
            OrganizacionSocial::create($organizacion);
        }

        $this->command->info('✅ ' . count($organizacionesSociales) . ' ORGANIZACIONES SOCIALES CREADAS EXITOSAMENTE!');
        $this->command->info('🏢 SE INCLUYERON ORGANIZACIONES DE 7 SECTORES:');
        $this->command->info('   🌽 ARTESANAL Y PRODUCTIVO (10 ORGANIZACIONES)');
        $this->command->info('   🌽 AGROPECUARIO Y AGROINDUSTRIAL (9 ORGANIZACIONES)');
        $this->command->info('   🚚 TRANSPORTE (5 ORGANIZACIONES)');
        $this->command->info('   🏭 INDUSTRIAL, COMERCIAL Y EMPRESARIAL (8 ORGANIZACIONES)');
        $this->command->info('   ⛏ MINERO (4 ORGANIZACIONES)');
        $this->command->info('   👷 LABORAL Y SINDICAL ECONÓMICO (5 ORGANIZACIONES)');
        $this->command->info('   🧺 ECONOMÍA POPULAR Y SOLIDARIA (6 ORGANIZACIONES)');
    }
}